language: ruby

sudo: false

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1

gemfile:
  - gemfiles/Gemfile.activemodel-5.2
  - gemfiles/Gemfile.activemodel-6.0

matrix:
  exclude:
    - gemfile: gemfiles/Gemfile.activemodel-5.2
      rvm: 1.9.3
    - gemfile: gemfiles/Gemfile.activemodel-5.2
      rvm: 2.0.0
    - gemfile: gemfiles/Gemfile.activemodel-5.2
      rvm: 2.1.6
    - gemfile: gemfiles/Gemfile.activemodel-6.0
      rvm: 1.9.3
    - gemfile: gemfiles/Gemfile.activemodel-6.0
      rvm: 2.0.0
    - gemfile: gemfiles/Gemfile.activemodel-6.0
      rvm: 2.1.6
    - gemfile: gemfiles/Gemfile.activemodel-6.0
      rvm: 2.2.10
    - gemfile: gemfiles/Gemfile.activemodel-6.0
      rvm: 2.3.7
    - gemfile: gemfiles/Gemfile.activemodel-6.0
      rvm: 2.4.3

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script: "echo 'COME ON!' && bundle exec rake spec"
